// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { appConfig, assertPublicConfig } from '@/config';

assertPublicConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database, "scripture">(appConfig.supabase.url, appConfig.supabase.publishableKey, {
  db: {
    schema: "scripture",
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export const scripture = supabase.schema("scripture");
